# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/ubuntu/new_lab/my_lab5_1/my_lab5.cache/wt [current_project]
set_property parent.project_path /home/ubuntu/new_lab/my_lab5_1/my_lab5.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/ubuntu/new_lab/my_lab5_1/my_lab5.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files /home/ubuntu/new_lab/my_lab5_1/my_lab5.srcs/sources_1/imports/ubuntu/new_lab/lab5_1/hazard_test.coe
add_files /home/ubuntu/new_lab/my_lab5_1/my_lab5.srcs/sources_1/imports/ubuntu/new_lab/lab5_1/D_MEM.coe
add_files /home/ubuntu/new_lab/my_lab5_1/my_lab5.srcs/sources_1/imports/ubuntu/桌面/data_harzard_test.coe
add_files /home/ubuntu/new_lab/my_lab5_1/my_lab5.srcs/sources_1/imports/ubuntu/桌面/test1.coe
add_files /home/ubuntu/new_lab/my_lab5_1/my_lab5.srcs/sources_1/imports/ubuntu/桌面/hazard.coe
add_files /home/ubuntu/桌面/fib.coe
read_verilog -library xil_defaultlib {
  /home/ubuntu/new_lab/my_lab5_1/my_lab5.srcs/sources_1/imports/ubuntu/new_lab/lab5_1/lab5_1.srcs/sources_1/new/EX_MEM.v
  /home/ubuntu/new_lab/my_lab5_1/my_lab5.srcs/sources_1/imports/ubuntu/new_lab/lab5_1/lab5_1.srcs/sources_1/new/ID_EX.v
  /home/ubuntu/new_lab/my_lab5_1/my_lab5.srcs/sources_1/imports/ubuntu/new_lab/lab5_1/lab5_1.srcs/sources_1/new/IF_ID.v
  /home/ubuntu/new_lab/my_lab5_1/my_lab5.srcs/sources_1/imports/ubuntu/new_lab/lab5_1/lab5_1.srcs/sources_1/new/MEM_WB.v
  /home/ubuntu/new_lab/my_lab5_1/my_lab5.srcs/sources_1/imports/ubuntu/new_lab/lab5_1/lab5_1.srcs/sources_1/new/add.v
  /home/ubuntu/new_lab/my_lab5_1/my_lab5.srcs/sources_1/imports/ubuntu/new_lab/lab5_1/lab5_1.srcs/sources_1/new/alu.v
  /home/ubuntu/new_lab/my_lab5_1/my_lab5.srcs/sources_1/imports/ubuntu/new_lab/lab5_1/lab5_1.srcs/sources_1/new/control.v
  /home/ubuntu/new_lab/my_lab5_1/my_lab5.srcs/sources_1/imports/ubuntu/new_lab/lab5_1/lab5_1.srcs/sources_1/new/cpu.v
  /home/ubuntu/new_lab/my_lab5_1/my_lab5.srcs/sources_1/imports/ubuntu/new_lab/lab5_1/lab5_1.srcs/sources_1/new/forwarding.v
  /home/ubuntu/new_lab/my_lab5_1/my_lab5.srcs/sources_1/imports/ubuntu/new_lab/lab5_1/lab5_1.srcs/sources_1/new/hazard.v
  /home/ubuntu/new_lab/my_lab5_1/my_lab5.srcs/sources_1/imports/ubuntu/new_lab/lab5_1/lab5_1.srcs/sources_1/new/imm_gen.v
  /home/ubuntu/new_lab/my_lab5_1/my_lab5.srcs/sources_1/imports/ubuntu/new_lab/lab5_1/lab5_1.srcs/sources_1/new/mux2.v
  /home/ubuntu/new_lab/my_lab5_1/my_lab5.srcs/sources_1/imports/ubuntu/new_lab/lab5_1/lab5_1.srcs/sources_1/new/mux3.v
  /home/ubuntu/new_lab/my_lab5_1/my_lab5.srcs/sources_1/imports/ubuntu/new_lab/lab5_1/lab5_1.srcs/sources_1/new/pdu.v
  /home/ubuntu/new_lab/my_lab5_1/my_lab5.srcs/sources_1/imports/ubuntu/new_lab/lab5_1/lab5_1.srcs/sources_1/new/program_counter.v
  /home/ubuntu/new_lab/my_lab5_1/my_lab5.srcs/sources_1/imports/ubuntu/new_lab/lab5_1/lab5_1.srcs/sources_1/new/regfile.v
  /home/ubuntu/new_lab/my_lab5_1/my_lab5.srcs/sources_1/imports/ubuntu/new_lab/lab5_1/lab5_1.srcs/sources_1/new/register.v
  /home/ubuntu/new_lab/my_lab5_1/my_lab5.srcs/sources_1/imports/ubuntu/new_lab/lab5_1/lab5_1.srcs/sources_1/new/shift_left.v
  /home/ubuntu/new_lab/my_lab5_1/my_lab5.srcs/sources_1/imports/ubuntu/new_lab/lab5_1/lab5_1.srcs/sources_1/new/top.v
}
read_ip -quiet /home/ubuntu/new_lab/my_lab5_1/my_lab5.srcs/sources_1/ip/mem_inst/mem_inst.xci
set_property used_in_implementation false [get_files -all /home/ubuntu/new_lab/my_lab5_1/my_lab5.srcs/sources_1/ip/mem_inst/mem_inst_ooc.xdc]

read_ip -quiet /home/ubuntu/new_lab/my_lab5_1/my_lab5.srcs/sources_1/ip/mem_data/mem_data.xci
set_property used_in_implementation false [get_files -all /home/ubuntu/new_lab/my_lab5_1/my_lab5.srcs/sources_1/ip/mem_data/mem_data_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/ubuntu/new_lab/my_lab5_1/my_lab5.srcs/constrs_1/imports/new/top_cons.xdc
set_property used_in_implementation false [get_files /home/ubuntu/new_lab/my_lab5_1/my_lab5.srcs/constrs_1/imports/new/top_cons.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
