# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ubuntu/new_lab/my_lab5_1/my_lab5.srcs/sources_1/ip/mem_inst/mem_inst.xci
# IP: The module: 'mem_inst' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ubuntu/new_lab/my_lab5_1/my_lab5.srcs/sources_1/ip/mem_inst/mem_inst_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mem_inst'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/ubuntu/new_lab/my_lab5_1/my_lab5.srcs/sources_1/ip/mem_inst/mem_inst.xci
# IP: The module: 'mem_inst' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ubuntu/new_lab/my_lab5_1/my_lab5.srcs/sources_1/ip/mem_inst/mem_inst_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mem_inst'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
